### PR TITLE
#1 resolved.clock icon added.AM-PM added.

### PR DESCRIPTION
**Pull request by onkarsrivastava**

### CODE REVIEW

**Comment by apu52** [comment]
@onkarsrivastava Please give some SS or some description what you have developed

**Comment by onkarsrivastava** [comment]
in main.js, used padStart() to assign 2 digits to each component of digital clock.
in index.html added bootstrap clock icon and fitted it into the parent container by modifying style.css.
in main.js applied ternary operation to display AM or PM according to hour of the day.

**Comment by apu52** [comment]
Good Work @onkarsrivastava

**Comment by onkarsrivastava** [comment]
Thanks @apu52

**Pull request merged**
